version: "3.8"

include:
  - proxy.yaml

services:
  web:
    image: cr.yandex/crpl7lkpal0fsunb5es0/python:hello
    restart:  always
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - DB_TABLE_NAME=requests
      - DB_HOST=172.20.0.10
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - default-authentication-plugin=mysql_native_password

  db:
    image: mysql:8
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.10
    ports:
      - 3306:3306
    env_file:
      - .env